<?php 
$pageTitle = "Chicken Game";
include 'header.php'; 
?>

<div class="container my-5">
    <div class="game-container">
        <h1 class="text-center mb-4" style="color: var(--primary-purple);">
            <i class="fas fa-feather me-2"></i>Chicken Run
        </h1>
        
        <div class="game-interface">
            <!-- Balance Display -->
            <div class="balance-display-game">
                <i class="fas fa-wallet me-2"></i>Balance: <span id="gameBalance">10,000</span> Coins
            </div>
            
            <!-- Game Status -->
            <div class="text-center mb-4">
                <div id="gameStatus" class="text-white" style="font-size: 1.2rem; font-weight: bold;">
                    Set your bet and click START GAME
                </div>
                <div id="multiplier" class="text-success" style="font-size: 1.5rem; font-weight: bold; margin-top: 0.5rem;">
                    Multiplier: 1.0x
                </div>
            </div>
            
            <!-- Chicken Grid -->
            <div class="chicken-grid-container">
                <div class="chicken-grid" id="chickenGrid">
                    <!-- Grid will be generated by JavaScript -->
                </div>
            </div>
            
            <!-- Bet Controls -->
            <div class="bet-controls mt-4">
                <label for="betAmount" class="text-white me-2">Bet Amount:</label>
                <input type="number" id="betAmount" class="bet-input" value="100" min="10" max="1000" step="10">
                <button id="startGameBtn" class="btn btn-primary btn-lg ms-3">
                    <i class="fas fa-play me-2"></i>START GAME
                </button>
                <button id="cashOutBtn" class="btn btn-success btn-lg ms-2" style="display:none;">
                    <i class="fas fa-money-bill me-2"></i>CASH OUT
                </button>
            </div>
            
            <!-- Game Info -->
            <div class="mt-4 text-center">
                <h5 class="text-white mb-3">How to Play</h5>
                <p class="text-white">Click on tiles to find safe spots ✓ and avoid the chickens 🐔. Each safe tile increases your multiplier. Cash out to win!</p>
            </div>
        </div>
        
        <div class="text-center mt-4">
            <a href="../games.php" class="btn btn-secondary">
                <i class="fas fa-arrow-left me-2"></i>Back to Games
            </a>
        </div>
    </div>
</div>

<style>
.chicken-grid-container {
    display: flex;
    justify-content: center;
    margin: 2rem 0;
}

.chicken-grid {
    display: grid;
    grid-template-columns: repeat(5, 1fr);
    gap: 0.5rem;
    background: rgba(0, 0, 0, 0.3);
    padding: 1rem;
    border-radius: 12px;
    border: 2px solid var(--accent-gold);
}

.chicken-tile {
    width: 60px;
    height: 60px;
    background: linear-gradient(135deg, #0066cc, #0052a3);
    border: 2px solid #ffff00;
    border-radius: 8px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 2rem;
    cursor: pointer;
    transition: all 0.3s ease;
    color: #ffff00;
    font-weight: bold;
}

.chicken-tile:hover:not(.revealed) {
    transform: scale(1.1);
    box-shadow: 0 0 15px #ffff00;
}

.chicken-tile.revealed {
    cursor: not-allowed;
}

.chicken-tile.safe {
    background: linear-gradient(135deg, #00ff00, #00cc00);
    border-color: #00ff00;
    color: white;
}

.chicken-tile.chicken {
    background: linear-gradient(135deg, #ff0000, #cc0000);
    border-color: #ff0000;
    color: white;
}

.chicken-tile:disabled {
    opacity: 0.7;
}
</style>

<script>
const GRID_SIZE = 25;
const CHICKEN_COUNT = 5;
let gameState = {
    started: false,
    grid: [],
    revealed: 0,
    multiplier: 1.0,
    bet: 100,
    balance: 10000
};

function initializeGame() {
    gameState.grid = [];
    for (let i = 0; i < GRID_SIZE; i++) {
        gameState.grid.push({
            isChicken: Math.random() < (CHICKEN_COUNT / GRID_SIZE),
            revealed: false
        });
    }
    gameState.revealed = 0;
    gameState.multiplier = 1.0;
    renderGrid();
}

function renderGrid() {
    const gridContainer = document.getElementById('chickenGrid');
    gridContainer.innerHTML = '';
    
    gameState.grid.forEach((tile, index) => {
        const tileEl = document.createElement('button');
        tileEl.className = 'chicken-tile';
        
        if (tile.revealed) {
            tileEl.classList.add('revealed');
            tileEl.textContent = tile.isChicken ? '🐔' : '✓';
            tileEl.classList.add(tile.isChicken ? 'chicken' : 'safe');
            tileEl.disabled = true;
        } else {
            tileEl.textContent = '?';
            tileEl.onclick = () => revealTile(index);
        }
        
        gridContainer.appendChild(tileEl);
    });
}

function revealTile(index) {
    if (!gameState.started || gameState.grid[index].revealed) return;
    
    gameState.grid[index].revealed = true;
    
    if (gameState.grid[index].isChicken) {
        // Hit a chicken - game over
        casinoSounds.playLoss();
        document.getElementById('gameStatus').textContent = '🐔 GAME OVER! You hit a chicken!';
        document.getElementById('gameStatus').style.color = '#ff0000';
        gameState.started = false;
        revealAllTiles();
        document.getElementById('startGameBtn').style.display = 'inline-block';
        document.getElementById('cashOutBtn').style.display = 'none';
    } else {
        // Safe tile
        casinoSounds.playWin();
        gameState.revealed++;
        gameState.multiplier = 1 + (gameState.revealed * 0.5);
        document.getElementById('multiplier').textContent = `Multiplier: ${gameState.multiplier.toFixed(1)}x`;
        document.getElementById('gameStatus').textContent = `✓ Safe! Multiplier: ${gameState.multiplier.toFixed(1)}x`;
        document.getElementById('gameStatus').style.color = '#00ff00';
    }
    
    renderGrid();
}

function revealAllTiles() {
    gameState.grid.forEach(tile => tile.revealed = true);
    renderGrid();
}

function cashOut() {
    if (!gameState.started) return;
    
    casinoSounds.playJackpot();
    const winAmount = Math.floor(gameState.bet * gameState.multiplier);
    gameState.balance += winAmount;
    
    document.getElementById('gameBalance').textContent = gameState.balance.toLocaleString();
    document.getElementById('gameStatus').textContent = `💰 Cashed out! Won ${winAmount.toLocaleString()} coins!`;
    document.getElementById('gameStatus').style.color = '#ffff00';
    
    gameState.started = false;
    document.getElementById('startGameBtn').style.display = 'inline-block';
    document.getElementById('cashOutBtn').style.display = 'none';
}

function startGame() {
    const betAmount = parseInt(document.getElementById('betAmount').value);
    
    if (betAmount < 10) {
        document.getElementById('gameStatus').textContent = 'Minimum bet is 10 coins!';
        document.getElementById('gameStatus').style.color = '#ff0000';
        return;
    }
    
    if (betAmount > gameState.balance) {
        document.getElementById('gameStatus').textContent = 'Insufficient balance!';
        document.getElementById('gameStatus').style.color = '#ff0000';
        return;
    }
    
    gameState.bet = betAmount;
    gameState.balance -= betAmount;
    gameState.started = true;
    
    document.getElementById('gameBalance').textContent = gameState.balance.toLocaleString();
    document.getElementById('gameStatus').textContent = 'Click tiles to find safe spots!';
    document.getElementById('gameStatus').style.color = '#00ff00';
    document.getElementById('multiplier').textContent = 'Multiplier: 1.0x';
    
    document.getElementById('startGameBtn').style.display = 'none';
    document.getElementById('cashOutBtn').style.display = 'inline-block';
    document.getElementById('betAmount').disabled = true;
    
    casinoSounds.playClick();
    initializeGame();
}

document.getElementById('startGameBtn').addEventListener('click', startGame);
document.getElementById('cashOutBtn').addEventListener('click', cashOut);

// Initialize balance display
document.getElementById('gameBalance').textContent = gameState.balance.toLocaleString();
</script>

<?php include 'footer.php'; ?>
